version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Unit tests
          command: ./gradlew test